import sort_objects_by_property_and_position_imported from "./sort_objects_by_property_and_position";
import sort_objects_by_property_imported from "./sort_objects_by_property";

export const sort_objects_by_property_and_position = sort_objects_by_property_and_position_imported;
export const sort_objects_by_property = sort_objects_by_property_imported;
