import React from 'react';
import Head from 'next/head';
import styled from '@emotion/styled';
import CenterChildrenV from '@ps/ui/components/layout/CenterChildrenV';
import CenterChildrenH from '@ps/ui/components/layout/CenterChildrenH';
import Button from '@ps/ui/components/form/Button';
import Modal from '@ps/ui/components/content/Modal';

export default function Home() {
  const H1 = styled.h1`
    color: red;
  `;
  const [isOpen, setIsOpen] = React.useState(false);
  return (
    <div>
      <Head>
        <title>Styled Components</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <CenterChildrenV ss="height:100vh;">
          <p>
            <input placeholder="Hit Tab key to focus inside each field on this page." />
          </p>
          <p>
            <textarea>
              Ideally, the focus should be trapped inside the modal while the
              modal is opened. Hitting tab should navigate the form fields
              inside the modal.
            </textarea>
          </p>
          <Modal
            isOpen={isOpen}
            onClose={() => {
              setIsOpen(false);
            }}
          >
            <h2>Hello! This title is inside a modal</h2>
            <p>This is not finished. Just started. Please check back soon.</p>
          </Modal>
          <p>
            <Button
              onClick={() => {
                setIsOpen(true);
              }}
              variant="primary"
            >
              Open modal
            </Button>
          </p>
          <p>
            <textarea>
              Then, after the modal has closed, the focus should be returned to
              the button that opened the modal.
            </textarea>
          </p>
          <p>
            <input placeholder="Another input field to test focus with." />
          </p>
        </CenterChildrenV>
      </main>
    </div>
  );
}
