import React from 'react';
import HomeTemplate from 'components/templates/Home';
import Head from 'next/head';
import PageContext from 'context/Page';

export default function HomePage() {
  const pageContext = {};
  return (
    <PageContext.Provider value={pageContext}>
      <Head>
        <title>Styled Components</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeTemplate />
    </PageContext.Provider>
  );
}
