import HomeTemplate from 'components/templates/Home';
import Head from 'next/head';
import PageContext from 'context/Page';

export default function HomePage() {
  const pageContext = {
    topText: (
      <>
        Hi. Thanks for visiting! This site is my sandbox to try new ideas. I'd
        love to show you my latest projects. Really appreciate your feedback.
      </>
    ),
  };
  return (
    <PageContext.Provider value={pageContext}>
      <Head>
        <title>Styled Components</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeTemplate />
    </PageContext.Provider>
  );
}
