let todisable = [
  'css',
  'ref',
  'children',
  'className',
  'as',
  'style',
  'mqSm',
  'mqMd',
  'mqLg',
  'mqDesktop',
  'mqTablet',
  'mqMobile',
  'mqPhone',
  'mqSmallPhone',
  'mqLargeDesktop',
  'mqVeryLargeDesktop',
  'mqTinyPhone',
  'mqNotPhone',
  'mqLargeTablet',
  'mqIframe',
  'mqNotIframe',
  'mqWebview',
  'mqNotWebview',
  'mqAndroid',
  'mqIPhone',
  'mqIPad',
  'mqMac',
  'mqWindows',
  'mqLinux',
  'mqIOS',
  'mqLandscape',
  'mqPortrait',
  'variant',
  'viewBox',
];
let output = {} as any;
for (let key of todisable) {
  output[key] = { table: { disable: true } };
}
export default output;
