let todisable = [
  'css',
  'ref',
  'children',
  'className',
  'as',
  'style',
  'ssSm',
  'ssMd',
  'ssLg',
  'ssDesktop',
  'ssTablet',
  'ssMobile',
  'ssPhone',
  'ssSmallPhone',
  'ssLargeDesktop',
  'ssVeryLargeDesktop',
  'ssTinyPhone',
  'ssNotPhone',
  'ssLargeTablet',
  'ssIframe',
  'ssNotIframe',
  'ssWebview',
  'ssNotWebview',
  'ssAndroid',
  'ssIPhone',
  'ssIPad',
  'ssMac',
  'ssWindows',
  'ssLinux',
  'ssIOS',
  'ssLandscape',
  'ssPortrait',
  'variant',
  'viewBox',
];
let output = {} as any;
for (let key of todisable) {
  output[key] = { table: { disable: true } };
}
export default output;
